version: "3"
services:
  backend:
    image: hpistor/phoenix-backend
    restart: always
    ports:
      - "4000:4000"
    command: bash start.sh
    hostname: server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - ./backend/:/app
    networks:
      - slack
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    networks:
      - slack

  frontend:
    image: hpistor/react-frontend
    command: bash start.sh
    hostname: frontend
    environment:
      - REACT_APP_API_URL=server
    volumes:
      - ./frontend/:/app
    networks:
      - slack
    ports:
      - "80:3000"


networks:
  slack:
